# Site settings
title: Musings of a Data Monkey
email: joseph.lei@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles about my data research and other miscellaneous topics
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://josephlei.com" # the base hostname & protocol for your site
twitter_username: josephjlei
github_username:  josephlei
linkedin_username: josephlei2

# Build settings
markdown: kramdown

# description sentences appear in jekyll document head meta (for Google search results) and in your feed.xml site description.
